services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-seazone_user}:${POSTGRES_PASSWORD:-seazone_password}@postgres:5432/${POSTGRES_DB:-seazone_db}
      - DEBUG=${DEBUG:-true}
    volumes:
      - .:/app
    working_dir: /app
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - seazone-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-usr}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pwd}
      POSTGRES_DB: ${POSTGRES_DB:-db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - seazone-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-seazone_user} -d ${POSTGRES_DB:-seazone_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  seazone-network:
    driver: bridge